import csv
rows=list(csv.DictReader(open("cues.csv")))
TITLE={"M01":"The Lie","M02":"One Head Opens","M03":"No System","M04":"Look Up","M05":"Four Parts",
"M06":"The Trigger","M07":"Shatter","M08":"Colour Ladder","M09":"The Judgement","M10":"No Reset / The Flood",
"M11":"Several Hundred","M12":"Close"}
def mmss(x):
    x=float(x); return f"{int(x//60)}:{x%60:05.2f}"
out=[]
out.append("# The Sprinkler — Shooting Script\n")
out.append("Pilot 01 · Midnight Everyman / Hidden Systems · **1920×1080 · 24 fps**\n")
out.append("Generated from `cues.csv`. **Do not edit this file** — edit the CSV and re-render.\n")
out.append(f"VO: `sprinkvo2.mp3` · 280.76 s (4:40.76) · 6738 frames · 712 words · 152 wpm\n")
out.append("Timings are silence-anchored estimates from the locked VO (±0.5 s within a line, exact at pauses).\n")
out.append("**R cues are keyframes inside one continuous movement, not cuts** — the stage transforms, it never cuts. **H cues are discrete generated clips.**\n")
h=sum(1 for r in rows if r["tool"]=="H")
out.append(f"**{len(rows)} cues · {h} Higgsfield clips · {len(rows)-h} Remotion keyframes across 12 movement components**\n")
out.append("\n---\n")
cur=None
for r in rows:
    if r["movement"]!=cur:
        cur=r["movement"]
        g=[x for x in rows if x["movement"]==cur]
        d=float(g[-1]["t_out"])-float(g[0]["t_in"])
        out.append(f"\n## {cur} · {TITLE[cur]}\n")
        out.append(f"`{mmss(g[0]['t_in'])} – {mmss(g[-1]['t_out'])}` · {d:.2f}s · frames **{g[0]['f_in']}–{g[-1]['f_out']}** ({int(g[-1]['f_out'])-int(g[0]['f_in'])}f) · {len(g)} cues · {sum(1 for x in g if x['tool']=='H')} H\n")
        out.append("| # | In | Dur | Frames | Tool | Observer | On screen | Visual | VO |")
        out.append("|---|---|---|---|---|---|---|---|---|")
    obs=r["observer"] or "—"
    on=r["onscreen"] or "—"
    vo=r["vo"].replace("|","/")
    if len(vo)>90: vo=vo[:88]+"…"
    out.append(f"| {r['cue']} | {mmss(r['t_in'])} | {r['dur']}s | {r['f_in']}–{r['f_out']} | **{r['tool']}** | {obs} | {on} | {r['description']} | {vo} |")
out.append("\n---\n\n## Observer appearances\n")
out.append("Rule: **the Observer never explains and never knows.** He walks under it, misses it, is saved by it, and installs it wrong.\n")
out.append("| Cue | Time | Beat | What he does |")
out.append("|---|---|---|---|")
LAB={"cinema":"Belief","soaked":"Belief","walks-under":"Orientation","oblivious":"Danger",
"under-dry":"Comprehension","installer":"Pathos","looks-up":"Close","cel:thinkChin":"Aside"}
for r in rows:
    if r["observer"]:
        out.append(f"| {r['cue']} | {mmss(r['t_in'])} | {LAB.get(r['observer'],'—')} | {r['description']} |")
tot=sum(float(r["dur"]) for r in rows if r["observer"])
out.append(f"\nTotal Observer screen time: **{tot:.1f}s** ({tot/280.76*100:.1f}% of runtime).\n")
out.append("\n## Flags\n")
sh=[r for r in rows if r["tool"]=="H" and float(r["dur"])<2.5]
out.append(f"- **{len(sh)} Higgsfield cues under 2.5 s** — extend or merge with a neighbour before generating; sub-2.5 s generated clips are wasteful and read as flicker: {', '.join(r['cue'] for r in sh)}")
out.append("- `M04` cue 25 says **SINCE 1994** — placeholder. Replace with a real year or cut the chip.")
out.append("- Blue/purple/black bulb values shown at 141/182/227 °C — verify against the bulb chart before locking the swatch row.")
out.append("- All `status` fields are `slug`. Update to `generated` / `approved` in the CSV as assets land.")
open("shooting-script.md","w").write("\n".join(out))
print(f"{len(rows)} rows rendered")
print("H cues < 2.5s:", [(r['cue'],r['dur']) for r in sh])
