export const cues = [
    {
        "cue":  "01",
        "movement":  "M01",
        "t_in":  "0.000",
        "t_out":  "2.083",
        "dur":  "2.083",
        "f_in":  "0",
        "f_out":  "50",
        "frames":  "50",
        "v1_tool":  "H",
        "tool":  "H",
        "source_id":  "HG-01",
        "treatment":  "Full-frame generated performance",
        "observer":  "cinema",
        "onscreen":  "",
        "description":  "Cinema interior, UPA flat. Observer in a seat, up-lit by screen glow, delighted",
        "vo":  "You\u0027ve seen it in movies a hundred times.",
        "status":  "approved"
    },
    {
        "cue":  "02",
        "movement":  "M01",
        "t_in":  "2.083",
        "t_out":  "4.500",
        "dur":  "2.417",
        "f_in":  "50",
        "f_out":  "108",
        "frames":  "58",
        "v1_tool":  "H",
        "tool":  "H",
        "source_id":  "HG-02",
        "treatment":  "Full-frame generated insert",
        "observer":  "",
        "onscreen":  "",
        "description":  "Hand raises a lighter beneath a sprinkler head, flame flickers, ominous",
        "vo":  "Someone holds a lighter up to a sprinkler head.",
        "status":  "slug"
    },
    {
        "cue":  "03",
        "movement":  "M01",
        "t_in":  "4.500",
        "t_out":  "10.792",
        "dur":  "6.292",
        "f_in":  "108",
        "f_out":  "259",
        "frames":  "151",
        "v1_tool":  "H",
        "tool":  "H",
        "source_id":  "HG-03",
        "treatment":  "Source opening span",
        "observer":  "",
        "onscreen":  "",
        "description":  "Wide: every head on the ceiling bursts at once, full deluge, movie logic",
        "vo":  "The entire building erupts in a wild torrent of water — every sprinkler head, all at once.",
        "status":  "slug"
    },
    {
        "cue":  "04",
        "movement":  "M01",
        "t_in":  "10.792",
        "t_out":  "15.542",
        "dur":  "4.750",
        "f_in":  "259",
        "f_out":  "373",
        "frames":  "114",
        "v1_tool":  "H",
        "tool":  "H",
        "source_id":  "HG-03",
        "treatment":  "Continue source / alternate crop",
        "observer":  "soaked",
        "onscreen":  "",
        "description":  "Observer soaked, papers flying past him, hero silhouette runs through spray",
        "vo":  "Everyone is soaked, papers fly, and the hero escapes in the confusion.",
        "status":  "slug"
    },
    {
        "cue":  "05",
        "movement":  "M01",
        "t_in":  "15.542",
        "t_out":  "17.542",
        "dur":  "2.000",
        "f_in":  "373",
        "f_out":  "421",
        "frames":  "48",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "MOVIE MAGIC",
        "description":  "Freeze frame; stamp lands over the still",
        "vo":  "It\u0027s a wonderful scene.",
        "status":  "slug"
    },
    {
        "cue":  "06",
        "movement":  "M01",
        "t_in":  "17.542",
        "t_out":  "20.417",
        "dur":  "2.875",
        "f_in":  "421",
        "f_out":  "490",
        "frames":  "69",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "COMPLETE NONSENSE",
        "description":  "Hard cut. Coral stamp. Colour drains out of the scene to paper",
        "vo":  "It is also complete nonsense.",
        "status":  "slug"
    },
    {
        "cue":  "07",
        "movement":  "M02",
        "t_in":  "20.417",
        "t_out":  "22.708",
        "dur":  "2.292",
        "f_in":  "490",
        "f_out":  "545",
        "frames":  "55",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Wipe from paper to a real ceiling; camera settles",
        "vo":  "Here is what actually happens.",
        "status":  "slug"
    },
    {
        "cue":  "08",
        "movement":  "M02",
        "t_in":  "22.708",
        "t_out":  "24.542",
        "dur":  "1.833",
        "f_in":  "545",
        "f_out":  "589",
        "frames":  "44",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-04",
        "treatment":  "Generated plate + Remotion mechanism",
        "observer":  "",
        "onscreen":  "",
        "description":  "HG-04 ceiling plate. Remotion adds one accurate active head and the localized water cone.",
        "vo":  "One sprinkler head opens.",
        "status":  "slug"
    },
    {
        "cue":  "09",
        "movement":  "M02",
        "t_in":  "24.542",
        "t_out":  "27.583",
        "dur":  "3.042",
        "f_in":  "589",
        "f_out":  "662",
        "frames":  "73",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-04",
        "treatment":  "Same plate + Remotion push",
        "observer":  "",
        "onscreen":  "",
        "description":  "Continue HG-04. Remotion camera push isolates the active head directly above the fire.",
        "vo":  "That one. The one directly above the fire.",
        "status":  "slug"
    },
    {
        "cue":  "10",
        "movement":  "M02",
        "t_in":  "27.583",
        "t_out":  "32.708",
        "dur":  "5.125",
        "f_in":  "662",
        "f_out":  "785",
        "frames":  "123",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-04",
        "treatment":  "Same plate + Remotion reframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Continue HG-04. Remotion reframes across the dry heads; no new generated shot.",
        "vo":  "Every other head on that ceiling stays sealed, dry, and entirely uninterested.",
        "status":  "slug"
    },
    {
        "cue":  "11",
        "movement":  "M03",
        "t_in":  "32.708",
        "t_out":  "37.000",
        "dur":  "4.292",
        "f_in":  "785",
        "f_out":  "888",
        "frames":  "103",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "NO CONTROL PANEL",
        "description":  "Control-panel icon assembles, then is struck through",
        "vo":  "Because there is no system. No panel deciding which heads to open.",
        "status":  "slug"
    },
    {
        "cue":  "12",
        "movement":  "M03",
        "t_in":  "37.000",
        "t_out":  "40.375",
        "dur":  "3.375",
        "f_in":  "888",
        "f_out":  "969",
        "frames":  "81",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Ceiling grid: each head resolves into an isolated node. No connecting lines are ever drawn",
        "vo":  "Every head on that ceiling is its own separate machine, and",
        "status":  "slug"
    },
    {
        "cue":  "13",
        "movement":  "M03",
        "t_in":  "40.375",
        "t_out":  "43.083",
        "dur":  "2.708",
        "f_in":  "969",
        "f_out":  "1034",
        "frames":  "65",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "ONE THING",
        "description":  "One node scales up, alone in frame",
        "vo":  "each one knows precisely one thing:",
        "status":  "slug"
    },
    {
        "cue":  "14",
        "movement":  "M03",
        "t_in":  "43.083",
        "t_out":  "46.208",
        "dur":  "3.125",
        "f_in":  "1034",
        "f_out":  "1109",
        "frames":  "75",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "local air temperature",
        "description":  "Thermometer ring closes around the single node",
        "vo":  "the temperature of the air immediately around it.",
        "status":  "slug"
    },
    {
        "cue":  "15",
        "movement":  "M03",
        "t_in":  "46.208",
        "t_out":  "50.208",
        "dur":  "4.000",
        "f_in":  "1109",
        "f_out":  "1205",
        "frames":  "96",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Top-down floorplan. Fire icon in one corner; heat gradient stays local",
        "vo":  "A fire in the corner of an office is a local event, not a building-wide one.",
        "status":  "slug"
    },
    {
        "cue":  "16",
        "movement":  "M03",
        "t_in":  "50.208",
        "t_out":  "54.625",
        "dur":  "4.417",
        "f_in":  "1205",
        "f_out":  "1311",
        "frames":  "106",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "1",
        "description":  "Counter appears beside the active head",
        "vo":  "And in a real fire, the usual number of heads that open is one.",
        "status":  "slug"
    },
    {
        "cue":  "17",
        "movement":  "M03",
        "t_in":  "54.625",
        "t_out":  "56.292",
        "dur":  "1.667",
        "f_in":  "1311",
        "f_out":  "1351",
        "frames":  "40",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "2 -\u003e 1",
        "description":  "Counter flickers to 2, settles back to 1",
        "vo":  "Occasionally two.",
        "status":  "slug"
    },
    {
        "cue":  "18",
        "movement":  "M03",
        "t_in":  "56.292",
        "t_out":  "58.583",
        "dur":  "2.292",
        "f_in":  "1351",
        "f_out":  "1406",
        "frames":  "55",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Grid recedes; the question opens up",
        "vo":  "So the question isn\u0027t how they all know.",
        "status":  "slug"
    },
    {
        "cue":  "19",
        "movement":  "M03",
        "t_in":  "58.583",
        "t_out":  "63.042",
        "dur":  "4.458",
        "f_in":  "1406",
        "f_out":  "1513",
        "frames":  "107",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "THAT ONE  /  THE OTHER 300",
        "description":  "Split comparison locks in",
        "vo":  "It\u0027s what is inside that one, that isn\u0027t inside the other three hundred.",
        "status":  "slug"
    },
    {
        "cue":  "20",
        "movement":  "M04",
        "t_in":  "63.042",
        "t_out":  "63.958",
        "dur":  "0.917",
        "f_in":  "1513",
        "f_out":  "1535",
        "frames":  "22",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-05",
        "treatment":  "Source opening span",
        "observer":  "walks-under",
        "onscreen":  "",
        "description":  "Begin HG-05: locked corridor. Observer walks beneath the head without looking up.",
        "vo":  "Look up.",
        "status":  "slug"
    },
    {
        "cue":  "21",
        "movement":  "M04",
        "t_in":  "63.958",
        "t_out":  "66.250",
        "dur":  "2.292",
        "f_in":  "1535",
        "f_out":  "1590",
        "frames":  "55",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-05",
        "treatment":  "Same source + crop + accurate overlay",
        "observer":  "",
        "onscreen":  "",
        "description":  "Crop into HG-05 plate. Remotion supplies the accurate brass-head macro.",
        "vo":  "There it is: a small brass fitting",
        "status":  "slug"
    },
    {
        "cue":  "22",
        "movement":  "M04",
        "t_in":  "66.250",
        "t_out":  "71.000",
        "dur":  "4.750",
        "f_in":  "1590",
        "f_out":  "1704",
        "frames":  "114",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-05",
        "treatment":  "Continue source wide",
        "observer":  "walks-under",
        "onscreen":  "",
        "description":  "Return to the HG-05 wide and continue the same walk-under performance.",
        "vo":  "you have walked underneath ten thousand times without once considering it.",
        "status":  "slug"
    },
    {
        "cue":  "23",
        "movement":  "M04",
        "t_in":  "71.000",
        "t_out":  "72.875",
        "dur":  "1.875",
        "f_in":  "1704",
        "f_out":  "1749",
        "frames":  "45",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Cutaway: ceiling tile peels back, pipe revealed above",
        "vo":  "Above it, a pipe.",
        "status":  "slug"
    },
    {
        "cue":  "24",
        "movement":  "M04",
        "t_in":  "72.875",
        "t_out":  "77.125",
        "dur":  "4.250",
        "f_in":  "1749",
        "f_out":  "1851",
        "frames":  "102",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "HIGH PRESSURE",
        "description":  "Water fills the pipe; pressure gauge swings",
        "vo":  "Inside the pipe, water — at high pressure, directly over your head,",
        "status":  "slug"
    },
    {
        "cue":  "25",
        "movement":  "M04",
        "t_in":  "77.125",
        "t_out":  "79.500",
        "dur":  "2.375",
        "f_in":  "1851",
        "f_out":  "1908",
        "frames":  "57",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "SINCE 1994",
        "description":  "Date tick backwards to construction",
        "vo":  "since the day the building went up.",
        "status":  "slug"
    },
    {
        "cue":  "26",
        "movement":  "M05",
        "t_in":  "79.500",
        "t_out":  "80.625",
        "dur":  "1.125",
        "f_in":  "1908",
        "f_out":  "1935",
        "frames":  "27",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "FOUR PARTS",
        "description":  "Exploded view assembles",
        "vo":  "Four parts.",
        "status":  "slug"
    },
    {
        "cue":  "27",
        "movement":  "M05",
        "t_in":  "80.625",
        "t_out":  "82.750",
        "dur":  "2.125",
        "f_in":  "1935",
        "f_out":  "1986",
        "frames":  "51",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "1 · FRAME",
        "description":  "Frame highlighted, screwed into the pipe",
        "vo":  "A frame, screwed into the pipe.",
        "status":  "slug"
    },
    {
        "cue":  "28",
        "movement":  "M05",
        "t_in":  "82.750",
        "t_out":  "84.667",
        "dur":  "1.917",
        "f_in":  "1986",
        "f_out":  "2032",
        "frames":  "46",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "2 · CAP",
        "description":  "Cap highlighted, sealing the opening",
        "vo":  "A cap, sealing the opening.",
        "status":  "slug"
    },
    {
        "cue":  "29",
        "movement":  "M05",
        "t_in":  "84.667",
        "t_out":  "88.500",
        "dur":  "3.833",
        "f_in":  "2032",
        "f_out":  "2124",
        "frames":  "92",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "3 · DEFLECTOR",
        "description":  "Deflector disc highlighted; notches visible",
        "vo":  "A deflector — that flat, notched disc on the bottom.",
        "status":  "slug"
    },
    {
        "cue":  "30",
        "movement":  "M05",
        "t_in":  "88.500",
        "t_out":  "91.917",
        "dur":  "3.417",
        "f_in":  "2124",
        "f_out":  "2206",
        "frames":  "82",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "4 · BULB — under permanent compression",
        "description":  "Compression arrows animate between cap and frame",
        "vo":  "And wedged between the cap and the frame, under permanent compression,",
        "status":  "slug"
    },
    {
        "cue":  "31",
        "movement":  "M05",
        "t_in":  "91.917",
        "t_out":  "95.250",
        "dur":  "3.333",
        "f_in":  "2206",
        "f_out":  "2286",
        "frames":  "80",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "~ grain of rice",
        "description":  "Scale comparison beside the bulb",
        "vo":  "a glass bulb about the size of a grain of rice.",
        "status":  "slug"
    },
    {
        "cue":  "32",
        "movement":  "M05",
        "t_in":  "95.250",
        "t_out":  "98.125",
        "dur":  "2.875",
        "f_in":  "2286",
        "f_out":  "2355",
        "frames":  "69",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "glycerine-based liquid",
        "description":  "Macro cutaway; liquid fills the bulb",
        "vo":  "Inside the bulb: a glycerine-based liquid,",
        "status":  "slug"
    },
    {
        "cue":  "33",
        "movement":  "M05",
        "t_in":  "98.125",
        "t_out":  "100.542",
        "dur":  "2.417",
        "f_in":  "2355",
        "f_out":  "2413",
        "frames":  "58",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "One air bubble appears inside the liquid, labelled",
        "vo":  "and one small bubble of air.",
        "status":  "slug"
    },
    {
        "cue":  "34",
        "movement":  "M06",
        "t_in":  "100.542",
        "t_out":  "103.292",
        "dur":  "2.750",
        "f_in":  "2413",
        "f_out":  "2479",
        "frames":  "66",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Mechanism clock starts. Beat before the fire",
        "vo":  "That\u0027s the trigger. Now watch it work.",
        "status":  "slug"
    },
    {
        "cue":  "35",
        "movement":  "M06",
        "t_in":  "103.292",
        "t_out":  "104.125",
        "dur":  "0.833",
        "f_in":  "2479",
        "f_out":  "2499",
        "frames":  "20",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-06",
        "treatment":  "Generated plate + controlled flame",
        "observer":  "oblivious",
        "onscreen":  "",
        "description":  "Begin HG-06 office tableau. Remotion reinforces the small bin flame.",
        "vo":  "A bin ignites.",
        "status":  "slug"
    },
    {
        "cue":  "36",
        "movement":  "M06",
        "t_in":  "104.125",
        "t_out":  "107.542",
        "dur":  "3.417",
        "f_in":  "2499",
        "f_out":  "2581",
        "frames":  "82",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-06",
        "treatment":  "Continue source + smoke overlay",
        "observer":  "oblivious",
        "onscreen":  "",
        "description":  "Continue HG-06. Smoke overlay curls upward while Observer remains oblivious.",
        "vo":  "Smoke rises — and does nothing at all.",
        "status":  "slug"
    },
    {
        "cue":  "37",
        "movement":  "M06",
        "t_in":  "107.542",
        "t_out":  "109.333",
        "dur":  "1.792",
        "f_in":  "2581",
        "f_out":  "2624",
        "frames":  "43",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "NO SMOKE DETECTION",
        "description":  "Nose icon struck through",
        "vo":  "Sprinklers cannot smell.",
        "status":  "slug"
    },
    {
        "cue":  "38",
        "movement":  "M06",
        "t_in":  "109.333",
        "t_out":  "112.000",
        "dur":  "2.667",
        "f_in":  "2624",
        "f_out":  "2688",
        "frames":  "64",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "HEAT ONLY",
        "description":  "Thermometer confirms",
        "vo":  "They react to heat, and only heat.",
        "status":  "slug"
    },
    {
        "cue":  "39",
        "movement":  "M06",
        "t_in":  "112.000",
        "t_out":  "114.417",
        "dur":  "2.417",
        "f_in":  "2688",
        "f_out":  "2746",
        "frames":  "58",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Hot gas plume spreads flat across the ceiling plane",
        "vo":  "The hot gas spreads out across the ceiling and",
        "status":  "slug"
    },
    {
        "cue":  "40",
        "movement":  "M06",
        "t_in":  "114.417",
        "t_out":  "116.333",
        "dur":  "1.917",
        "f_in":  "2746",
        "f_out":  "2792",
        "frames":  "46",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Plume reaches the nearest head node",
        "vo":  "reaches the nearest head.",
        "status":  "slug"
    },
    {
        "cue":  "41",
        "movement":  "M06",
        "t_in":  "116.333",
        "t_out":  "118.875",
        "dur":  "2.542",
        "f_in":  "2792",
        "f_out":  "2853",
        "frames":  "61",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Macro: liquid expands inside the bulb",
        "vo":  "The liquid in the bulb begins to expand.",
        "status":  "slug"
    },
    {
        "cue":  "42",
        "movement":  "M06",
        "t_in":  "118.875",
        "t_out":  "120.375",
        "dur":  "1.500",
        "f_in":  "2853",
        "f_out":  "2889",
        "frames":  "36",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "The bubble shrinks",
        "vo":  "The bubble shrinks.",
        "status":  "slug"
    },
    {
        "cue":  "43",
        "movement":  "M06",
        "t_in":  "120.375",
        "t_out":  "122.417",
        "dur":  "2.042",
        "f_in":  "2889",
        "f_out":  "2938",
        "frames":  "49",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "0:10   0:20",
        "description":  "Countdown ticks",
        "vo":  "Ten seconds. Twenty.",
        "status":  "slug"
    },
    {
        "cue":  "44",
        "movement":  "M06",
        "t_in":  "122.417",
        "t_out":  "126.167",
        "dur":  "3.750",
        "f_in":  "2938",
        "f_out":  "3028",
        "frames":  "90",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Bubble gone. Liquid pressed hard against the glass",
        "vo":  "The bubble is gone now, the liquid has nowhere left to go, and the",
        "status":  "slug"
    },
    {
        "cue":  "45",
        "movement":  "M06",
        "t_in":  "126.167",
        "t_out":  "126.917",
        "dur":  "0.750",
        "f_in":  "3028",
        "f_out":  "3046",
        "frames":  "18",
        "v1_tool":  "H",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Remotion macro: intact thermal bulb holds under strain; refraction and stress lines intensify.",
        "vo":  "glass is holding —",
        "status":  "slug"
    },
    {
        "cue":  "46",
        "movement":  "M06",
        "t_in":  "126.917",
        "t_out":  "131.125",
        "dur":  "4.208",
        "f_in":  "3046",
        "f_out":  "3147",
        "frames":  "101",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "cel:thinkChin",
        "onscreen":  "",
        "description":  "Observer beat — unimpressed by how stubborn glass is",
        "vo":  "because glass, it turns out, is remarkably stubborn.",
        "status":  "slug"
    },
    {
        "cue":  "47",
        "movement":  "M06",
        "t_in":  "131.125",
        "t_out":  "132.875",
        "dur":  "1.750",
        "f_in":  "3147",
        "f_out":  "3189",
        "frames":  "42",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Hard suspense beat. Everything stops",
        "vo":  "Until it isn\u0027t.",
        "status":  "slug"
    },
    {
        "cue":  "48",
        "movement":  "M07",
        "t_in":  "132.875",
        "t_out":  "135.417",
        "dur":  "2.542",
        "f_in":  "3189",
        "f_out":  "3250",
        "frames":  "61",
        "v1_tool":  "H",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Controlled SVG/vector shatter from the bulb centre; fragments remain on the assembly axis.",
        "vo":  "The bulb shatters from the inside.",
        "status":  "slug"
    },
    {
        "cue":  "49",
        "movement":  "M07",
        "t_in":  "135.417",
        "t_out":  "137.292",
        "dur":  "1.875",
        "f_in":  "3250",
        "f_out":  "3295",
        "frames":  "45",
        "v1_tool":  "H",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Cap drops cleanly along the assembly axis in the existing sprinkler component.",
        "vo":  "The cap drops away.",
        "status":  "slug"
    },
    {
        "cue":  "50",
        "movement":  "M07",
        "t_in":  "137.292",
        "t_out":  "142.167",
        "dur":  "4.875",
        "f_in":  "3295",
        "f_out":  "3412",
        "frames":  "117",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "WAITING 30 YEARS",
        "description":  "Water released; the wait counter zeroes",
        "vo":  "The water, which has been waiting patiently for about thirty years, leaves —",
        "status":  "slug"
    },
    {
        "cue":  "51",
        "movement":  "M07",
        "t_in":  "142.167",
        "t_out":  "146.000",
        "dur":  "3.833",
        "f_in":  "3412",
        "f_out":  "3504",
        "frames":  "92",
        "v1_tool":  "H",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Accurate Remotion water path hits the deflector and resolves into a cone of spray.",
        "vo":  "strikes the deflector, breaks into a cone of spray,",
        "status":  "slug"
    },
    {
        "cue":  "52",
        "movement":  "M07",
        "t_in":  "146.000",
        "t_out":  "150.167",
        "dur":  "4.167",
        "f_in":  "3504",
        "f_out":  "3604",
        "frames":  "100",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Exponential fire curve climbing, doubling every half minute",
        "vo":  "and the fire, which had been roughly doubling in size every half minute,",
        "status":  "slug"
    },
    {
        "cue":  "53",
        "movement":  "M07",
        "t_in":  "150.167",
        "t_out":  "151.458",
        "dur":  "1.292",
        "f_in":  "3604",
        "f_out":  "3635",
        "frames":  "31",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Curve snaps flat the instant water lands",
        "vo":  "stops doubling.",
        "status":  "slug"
    },
    {
        "cue":  "54",
        "movement":  "M07",
        "t_in":  "151.458",
        "t_out":  "156.625",
        "dur":  "5.167",
        "f_in":  "3635",
        "f_out":  "3759",
        "frames":  "124",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-07",
        "treatment":  "Source opening span + layout overlay",
        "observer":  "under-dry",
        "onscreen":  "",
        "description":  "Begin HG-07 held tableau. Remotion establishes the wet head / dry neighbouring-head relationship.",
        "vo":  "Two metres away, the next head sits in the cool air doing absolutely nothing.",
        "status":  "slug"
    },
    {
        "cue":  "55",
        "movement":  "M07",
        "t_in":  "156.625",
        "t_out":  "157.958",
        "dur":  "1.333",
        "f_in":  "3759",
        "f_out":  "3791",
        "frames":  "32",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-07",
        "treatment":  "Hold/freeze same source",
        "observer":  "under-dry",
        "onscreen":  "",
        "description":  "Hold or freeze HG-07. Nothing changes; the stillness is the joke.",
        "vo":  "It will still be doing nothing",
        "status":  "slug"
    },
    {
        "cue":  "56",
        "movement":  "M07",
        "t_in":  "157.958",
        "t_out":  "160.042",
        "dur":  "2.083",
        "f_in":  "3791",
        "f_out":  "3841",
        "frames":  "50",
        "v1_tool":  "H",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Remain in the established layout; an emergency-light sweep and brigade icon mark arrival.",
        "vo":  "when the fire brigade arrives.",
        "status":  "slug"
    },
    {
        "cue":  "57",
        "movement":  "M07",
        "t_in":  "160.042",
        "t_out":  "162.542",
        "dur":  "2.500",
        "f_in":  "3841",
        "f_out":  "3901",
        "frames":  "60",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "THE WHOLE MECHANISM",
        "description":  "Checklist opens",
        "vo":  "And that is the whole mechanism.",
        "status":  "slug"
    },
    {
        "cue":  "58",
        "movement":  "M07",
        "t_in":  "162.542",
        "t_out":  "165.625",
        "dur":  "3.083",
        "f_in":  "3901",
        "f_out":  "3975",
        "frames":  "74",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "No sensor · No wiring · No computer",
        "description":  "Items strike in one at a time",
        "vo":  "No sensor. No wiring. No computer.",
        "status":  "slug"
    },
    {
        "cue":  "59",
        "movement":  "M07",
        "t_in":  "165.625",
        "t_out":  "169.792",
        "dur":  "4.167",
        "f_in":  "3975",
        "f_out":  "4075",
        "frames":  "100",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "No control panel · No decision of any kind",
        "description":  "Final items settle",
        "vo":  "No control panel. No decision of any kind.",
        "status":  "slug"
    },
    {
        "cue":  "60",
        "movement":  "M07",
        "t_in":  "169.792",
        "t_out":  "173.792",
        "dur":  "4.000",
        "f_in":  "4075",
        "f_out":  "4171",
        "frames":  "96",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Return to the macro bubble; it shrinks to nothing. Pull wide to a calm building",
        "vo":  "A bubble got smaller, and a building got saved.",
        "status":  "slug"
    },
    {
        "cue":  "61",
        "movement":  "M08",
        "t_in":  "173.792",
        "t_out":  "178.250",
        "dur":  "4.458",
        "f_in":  "4171",
        "f_out":  "4278",
        "frames":  "107",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Swatch row assembles across the frame",
        "vo":  "Now — those bulbs are colour-coded, because of course they are.",
        "status":  "slug"
    },
    {
        "cue":  "62",
        "movement":  "M08",
        "t_in":  "178.250",
        "t_out":  "180.917",
        "dur":  "2.667",
        "f_in":  "4278",
        "f_out":  "4342",
        "frames":  "64",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "ORANGE   57 °C / 135 °F",
        "description":  "Orange swatch expands, chip sets",
        "vo":  "Orange opens at fifty-seven degrees.",
        "status":  "slug"
    },
    {
        "cue":  "63",
        "movement":  "M08",
        "t_in":  "180.917",
        "t_out":  "183.042",
        "dur":  "2.125",
        "f_in":  "4342",
        "f_out":  "4393",
        "frames":  "51",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "RED   68 °C / 155 °F",
        "description":  "Red swatch",
        "vo":  "Red at sixty-eight.",
        "status":  "slug"
    },
    {
        "cue":  "64",
        "movement":  "M08",
        "t_in":  "183.042",
        "t_out":  "184.833",
        "dur":  "1.792",
        "f_in":  "4393",
        "f_out":  "4436",
        "frames":  "43",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "YELLOW   79 °C / 175 °F",
        "description":  "Yellow swatch",
        "vo":  "Yellow, seventy-nine.",
        "status":  "slug"
    },
    {
        "cue":  "65",
        "movement":  "M08",
        "t_in":  "184.833",
        "t_out":  "186.792",
        "dur":  "1.958",
        "f_in":  "4436",
        "f_out":  "4483",
        "frames":  "47",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "GREEN   93 °C / 200 °F",
        "description":  "Green swatch",
        "vo":  "Green, ninety-three.",
        "status":  "slug"
    },
    {
        "cue":  "66",
        "movement":  "M08",
        "t_in":  "186.792",
        "t_out":  "189.708",
        "dur":  "2.917",
        "f_in":  "4483",
        "f_out":  "4553",
        "frames":  "70",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "BLUE 141/286 · PURPLE 182/360 · BLACK 227/500",
        "description":  "Three high swatches added, chips smaller",
        "vo":  "Then blue, purple and black,",
        "status":  "slug"
    },
    {
        "cue":  "67",
        "movement":  "M08",
        "t_in":  "189.708",
        "t_out":  "194.292",
        "dur":  "4.583",
        "f_in":  "4553",
        "f_out":  "4663",
        "frames":  "110",
        "v1_tool":  "H",
        "tool":  "H",
        "source_id":  "HG-08",
        "treatment":  "Full-frame generated atmosphere",
        "observer":  "",
        "onscreen":  "",
        "description":  "Boiler room / commercial kitchen ceiling, heat haze — where 200 °F is an ordinary Tuesday",
        "vo":  "for rooms where ninety-three degrees is considered a normal Tuesday.",
        "status":  "slug"
    },
    {
        "cue":  "68",
        "movement":  "M09",
        "t_in":  "194.292",
        "t_out":  "196.708",
        "dur":  "2.417",
        "f_in":  "4663",
        "f_out":  "4721",
        "frames":  "58",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "A JUDGEMENT, NOT A SETTING",
        "description":  "Type beat over the cooling swatch row",
        "vo":  "And that colour is not a setting.",
        "status":  "slug"
    },
    {
        "cue":  "69",
        "movement":  "M09",
        "t_in":  "196.708",
        "t_out":  "201.208",
        "dur":  "4.500",
        "f_in":  "4721",
        "f_out":  "4829",
        "frames":  "108",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-09",
        "treatment":  "Source first edit span",
        "observer":  "installer",
        "onscreen":  "",
        "description":  "First span of HG-09. Installer studies the room; coloured bulb tray remains foreground context, not a handled prop.",
        "vo":  "It\u0027s a judgement. Somebody had to choose the bulb for the room.",
        "status":  "approved"
    },
    {
        "cue":  "70",
        "movement":  "M09",
        "t_in":  "201.208",
        "t_out":  "204.625",
        "dur":  "3.417",
        "f_in":  "4829",
        "f_out":  "4911",
        "frames":  "82",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-10",
        "treatment":  "Generated plate + accurate head overlay",
        "observer":  "",
        "onscreen":  "",
        "description":  "Begin HG-10 kitchen plate. Remotion places the accurate office-rated head above the fryer.",
        "vo":  "Put an office-rated head above a deep fat fryer",
        "status":  "slug"
    },
    {
        "cue":  "71",
        "movement":  "M09",
        "t_in":  "204.625",
        "t_out":  "206.708",
        "dur":  "2.083",
        "f_in":  "4911",
        "f_out":  "4961",
        "frames":  "50",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-10",
        "treatment":  "Continue source + activation overlay",
        "observer":  "",
        "onscreen":  "",
        "description":  "Continue HG-10. Remotion activates the head; hold on unimpressed staff reaction.",
        "vo":  "and it opens every lunchtime.",
        "status":  "slug"
    },
    {
        "cue":  "72",
        "movement":  "M09",
        "t_in":  "206.708",
        "t_out":  "209.875",
        "dur":  "3.167",
        "f_in":  "4961",
        "f_out":  "5037",
        "frames":  "76",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-11",
        "treatment":  "Generated plate + accurate head overlay",
        "observer":  "",
        "onscreen":  "",
        "description":  "Begin HG-11 quiet-office plate. Remotion places the oversized kitchen-rated head.",
        "vo":  "Put a kitchen-rated head in a quiet office and the room",
        "status":  "slug"
    },
    {
        "cue":  "73",
        "movement":  "M09",
        "t_in":  "209.875",
        "t_out":  "213.875",
        "dur":  "4.000",
        "f_in":  "5037",
        "f_out":  "5133",
        "frames":  "96",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-11",
        "treatment":  "Continue source + fire-state overlay",
        "observer":  "",
        "onscreen":  "",
        "description":  "Continue HG-11. Remotion grows the fire while the accurate head remains closed.",
        "vo":  "can be well alight before it notices anything unusual.",
        "status":  "slug"
    },
    {
        "cue":  "74",
        "movement":  "M09",
        "t_in":  "213.875",
        "t_out":  "220.083",
        "dur":  "6.208",
        "f_in":  "5133",
        "f_out":  "5282",
        "frames":  "149",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-09",
        "treatment":  "Source second edit span",
        "observer":  "installer",
        "onscreen":  "",
        "description":  "Second span of HG-09. Installer surveys the empty room and visibly guesses; no exact prop contact.",
        "vo":  "So somewhere, years ago, a person had to guess how hot your ceiling gets on an ordinary day —",
        "status":  "approved"
    },
    {
        "cue":  "75",
        "movement":  "M09",
        "t_in":  "220.083",
        "t_out":  "221.958",
        "dur":  "1.875",
        "f_in":  "5282",
        "f_out":  "5327",
        "frames":  "45",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-09",
        "treatment":  "Source tail / hold",
        "observer":  "installer",
        "onscreen":  "",
        "description":  "Tail of HG-09. He exits; hold on the empty room and selected head.",
        "vo":  "and then leave.",
        "status":  "approved"
    },
    {
        "cue":  "76",
        "movement":  "M10",
        "t_in":  "221.958",
        "t_out":  "225.917",
        "dur":  "3.958",
        "f_in":  "5327",
        "f_out":  "5422",
        "frames":  "95",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "SINGLE USE",
        "description":  "Head greys out and locks",
        "vo":  "And when one does finally go, it doesn\u0027t reset.",
        "status":  "slug"
    },
    {
        "cue":  "77",
        "movement":  "M10",
        "t_in":  "225.917",
        "t_out":  "229.250",
        "dur":  "3.333",
        "f_in":  "5422",
        "f_out":  "5502",
        "frames":  "80",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "NO SWITCH",
        "description":  "Toggle icon struck through",
        "vo":  "There\u0027s no switch. That head is finished.",
        "status":  "slug"
    },
    {
        "cue":  "78",
        "movement":  "M10",
        "t_in":  "229.250",
        "t_out":  "231.542",
        "dur":  "2.292",
        "f_in":  "5502",
        "f_out":  "5557",
        "frames":  "55",
        "v1_tool":  "H",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Remotion object insert: spanner and replacement head enter as separate layers; no hands required.",
        "vo":  "Somebody arrives with a spanner,",
        "status":  "slug"
    },
    {
        "cue":  "79",
        "movement":  "M10",
        "t_in":  "231.542",
        "t_out":  "233.250",
        "dur":  "1.708",
        "f_in":  "5557",
        "f_out":  "5598",
        "frames":  "41",
        "v1_tool":  "H",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Exploded side view: the replacement head rotates into the threaded pipe.",
        "vo":  "screws in a new one,",
        "status":  "slug"
    },
    {
        "cue":  "80",
        "movement":  "M10",
        "t_in":  "233.250",
        "t_out":  "235.667",
        "dur":  "2.417",
        "f_in":  "5598",
        "f_out":  "5656",
        "frames":  "58",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "New head settles. The wait restarts from zero",
        "vo":  "and the new one starts waiting too.",
        "status":  "slug"
    },
    {
        "cue":  "81",
        "movement":  "M10",
        "t_in":  "235.667",
        "t_out":  "239.333",
        "dur":  "3.667",
        "f_in":  "5656",
        "f_out":  "5744",
        "frames":  "88",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "WATER DAMAGE?",
        "description":  "Comparison chart opens",
        "vo":  "As for the water damage everybody worries about — a sprinkler head",
        "status":  "slug"
    },
    {
        "cue":  "82",
        "movement":  "M10",
        "t_in":  "239.333",
        "t_out":  "242.958",
        "dur":  "3.625",
        "f_in":  "5744",
        "f_out":  "5831",
        "frames":  "87",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "SPRINKLER   60 L/min",
        "description":  "Sprinkler bar grows and settles",
        "vo":  "puts out somewhere around sixty litres a minute.",
        "status":  "slug"
    },
    {
        "cue":  "83",
        "movement":  "M10",
        "t_in":  "242.958",
        "t_out":  "246.958",
        "dur":  "4.000",
        "f_in":  "5831",
        "f_out":  "5927",
        "frames":  "96",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "FIREHOSE   600–1200 L/min",
        "description":  "Firehose bar dwarfs it, runs off frame",
        "vo":  "A firefighter\u0027s hose puts out ten to twenty times that.",
        "status":  "slug"
    },
    {
        "cue":  "84",
        "movement":  "M10",
        "t_in":  "246.958",
        "t_out":  "252.500",
        "dur":  "5.542",
        "f_in":  "5927",
        "f_out":  "6060",
        "frames":  "133",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "THE SPRINKLER PREVENTS THE FLOOD",
        "description":  "Inversion lands",
        "vo":  "The sprinkler isn\u0027t the flood. The sprinkler is what prevents the flood.",
        "status":  "slug"
    },
    {
        "cue":  "85",
        "movement":  "M11",
        "t_in":  "252.500",
        "t_out":  "255.375",
        "dur":  "2.875",
        "f_in":  "6060",
        "f_out":  "6129",
        "frames":  "69",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Pull back to the full ceiling grid; every head a separate dot",
        "vo":  "So the ceiling above you is not one system.",
        "status":  "slug"
    },
    {
        "cue":  "86",
        "movement":  "M11",
        "t_in":  "255.375",
        "t_out":  "258.417",
        "dur":  "3.042",
        "f_in":  "6129",
        "f_out":  "6202",
        "frames":  "73",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Dots pulse individually, out of phase. No lines between them",
        "vo":  "It\u0027s several hundred entirely separate ones,",
        "status":  "slug"
    },
    {
        "cue":  "87",
        "movement":  "M11",
        "t_in":  "258.417",
        "t_out":  "261.500",
        "dur":  "3.083",
        "f_in":  "6202",
        "f_out":  "6276",
        "frames":  "74",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "its own small glass fuse",
        "description":  "One dot glows",
        "vo":  "each with its own small glass fuse,",
        "status":  "slug"
    },
    {
        "cue":  "88",
        "movement":  "M11",
        "t_in":  "261.500",
        "t_out":  "266.583",
        "dur":  "5.083",
        "f_in":  "6276",
        "f_out":  "6398",
        "frames":  "122",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "",
        "description":  "Camera drifts across inert dots, minding their own business",
        "vo":  "each minding its own business, none of them talking to each other.",
        "status":  "slug"
    },
    {
        "cue":  "89",
        "movement":  "M11",
        "t_in":  "266.583",
        "t_out":  "268.958",
        "dur":  "2.375",
        "f_in":  "6398",
        "f_out":  "6455",
        "frames":  "57",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "NOTHING IS WATCHING",
        "description":  "Type over the empty grid",
        "vo":  "Nothing up there is watching you.",
        "status":  "slug"
    },
    {
        "cue":  "90",
        "movement":  "M11",
        "t_in":  "268.958",
        "t_out":  "271.750",
        "dur":  "2.792",
        "f_in":  "6455",
        "f_out":  "6522",
        "frames":  "67",
        "v1_tool":  "R",
        "tool":  "R",
        "source_id":  "",
        "treatment":  "Native movement keyframe",
        "observer":  "",
        "onscreen":  "NOTHING IS DECIDING",
        "description":  "Grid fades toward paper",
        "vo":  "Nothing is deciding anything.",
        "status":  "slug"
    },
    {
        "cue":  "91",
        "movement":  "M12",
        "t_in":  "271.750",
        "t_out":  "273.125",
        "dur":  "1.375",
        "f_in":  "6522",
        "f_out":  "6555",
        "frames":  "33",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-12",
        "treatment":  "Generated macro + controlled overlay",
        "observer":  "",
        "onscreen":  "",
        "description":  "Begin HG-12 macro plate. Remotion isolates the bulb and adds controlled pressure cues.",
        "vo":  "It is a piece of glass,",
        "status":  "approved"
    },
    {
        "cue":  "92",
        "movement":  "M12",
        "t_in":  "273.125",
        "t_out":  "278.333",
        "dur":  "5.208",
        "f_in":  "6555",
        "f_out":  "6680",
        "frames":  "125",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-12",
        "treatment":  "Continue source + Remotion push",
        "observer":  "",
        "onscreen":  "",
        "description":  "Continue HG-12 with a slow Remotion push and restrained surface-tension treatment.",
        "vo":  "holding back a river, waiting for something to get warm.",
        "status":  "approved"
    },
    {
        "cue":  "93",
        "movement":  "M12",
        "t_in":  "278.333",
        "t_out":  "280.750",
        "dur":  "2.417",
        "f_in":  "6680",
        "f_out":  "6738",
        "frames":  "58",
        "v1_tool":  "H",
        "tool":  "H+R",
        "source_id":  "HG-05",
        "treatment":  "Reuse source frame + approved cel",
        "observer":  "looks-up",
        "onscreen":  "",
        "description":  "Reuse the HG-05 corridor plate. Stage approved `inspectForward` cel beneath the head; slow push and fade.",
        "vo":  "Look up. It\u0027s still there.",
        "status":  "slug"
    }
];
